#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sinegen.vcd

# run Verilator to translate Verlig into C++, including C++ testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

# build C++ project via make file automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run the executable simulation file
obj_dir/Vsinegen